### ISSUE TITLE
[Code][Feature] Movement: Swimming 

### ISSUE THREAD

**Issue by wail** [OpenTournament/OpenTournament#146]
Super-story to wrap up a series of features needed to close out Movement's most glaring rough edge.

- [ ] OT-#142 : Swimming Exit Jump/Ledge-Hop
- [ ] OT-#143 : Swimming - Water Footsteps & InWater State
- [ ] OT-#144 : Movement: Swimming Drowning Mechanic
- [ ] OT-#145 : Swimming Dodging Mechanic
